<?xml version="1.0" encoding="utf-8"?><Database Name="Farmacia" Class="DbLibraryEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=Farmacia;Integrated Security=True" SettingsObjectName="CapaDatos.Properties.Settings" SettingsPropertyName="FarmaciaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cliente" Member="Clientes">
    <Type Name="Cliente">
      <Column Name="IDcliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DNI" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Edad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Cliente_Factura" Member="Facturas" ThisKey="IDcliente" OtherKey="IDcliente" Type="Factura" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id_user" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CodNivel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Empleado" Member="Empleados">
    <Type Name="Empleado">
      <Column Name="IDempleado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DNI" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IDfarmacia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Empleado_Factura" Member="Facturas" ThisKey="IDempleado" OtherKey="IDempleado" Type="Factura" />
      <Association Name="Farmacia_Empleado" Member="Farmacia" ThisKey="IDfarmacia" OtherKey="IDfarmacia" Type="Farmacia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Factura" Member="Facturas">
    <Type Name="Factura">
      <Column Name="IDfactura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodeFactura" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDcliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDempleado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_Factura" Member="Cliente" ThisKey="IDcliente" OtherKey="IDcliente" Type="Cliente" IsForeignKey="true" />
      <Association Name="Empleado_Factura" Member="Empleado" ThisKey="IDempleado" OtherKey="IDempleado" Type="Empleado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Farmaceutico" Member="Farmaceuticos">
    <Type Name="Farmaceutico">
      <Column Name="IDfarmaceutico" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Fechavencimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Precio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TF" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDfarmacia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Farmacia_Farmaceutico" Member="Farmacia" ThisKey="IDfarmacia" OtherKey="IDfarmacia" Type="Farmacia" IsForeignKey="true" />
      <Association Name="Tipo_Farmaceutico_Farmaceutico" Member="Tipo_Farmaceutico" ThisKey="ID_TF" OtherKey="ID_TF" Type="Tipo_Farmaceutico" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Farmacia" Member="Farmacias">
    <Type Name="Farmacia">
      <Column Name="IDfarmacia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Calle" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Sector" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Provincia" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Farmacia_Empleado" Member="Empleados" ThisKey="IDfarmacia" OtherKey="IDfarmacia" Type="Empleado" />
      <Association Name="Farmacia_Farmaceutico" Member="Farmaceuticos" ThisKey="IDfarmacia" OtherKey="IDfarmacia" Type="Farmaceutico" />
    </Type>
  </Table>
  <Table Name="dbo.Tipo_Farmaceutico" Member="Tipo_Farmaceuticos">
    <Type Name="Tipo_Farmaceutico">
      <Column Name="ID_TF" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tipofarmaceutico" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Tipo_Farmaceutico_Farmaceutico" Member="Farmaceuticos" ThisKey="ID_TF" OtherKey="ID_TF" Type="Farmaceutico" />
    </Type>
  </Table>
</Database>